platform :ios, '9.0'

target 'MyOneDemo' do
pod 'Masonry', '~> 1.0.1'
pod 'SDWebImage', '~> 3.8.1'
pod 'GMCPagingScrollView', '~> 1.0.3'
pod 'SDWebImage', '~> 3.8.1'
pod 'SDCycleScrollView', '~>1.65'
pod 'UITableView+FDTemplateLayoutCell', '~>1.4'
end
